services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: rentify
      JWT_SECRET_KEY: your-super-secret-key-change-in-production
      GEMINI_KEY: your-gemini-api-key
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
